Fix coverage test failure
Was failing with

    tests/test_ast.py:71: in <module>
        @parametrize_nodes()
    tests/test_ast.py:60: in parametrize_nodes
        nodes = [_instantiate_node(node_type) for node_type in node_types]
    tests/test_ast.py:55: in _instantiate_node
        return node_type(*([""] * len(node_type._fields)))
    E   TypeError: NodeList.__init__() missing 1 required positional argument: 'body'

coverage package adds a coverage.parser.NodeList subclass. See
https://github.com/nedbat/coveragepy/commit/0accb68cd9ac353bd5464750987e02012bdb8e0c